let studentName = "ravali";
let studentCast = "reddy";
let mathsMarks = 54;
let studentVillage = "pillarikuppam ";
console.log("-- - what type of data---- ");
console.log(typeof studentName);
console.log(typeof mathsMarks);
console.log(studentName + studentCast);
console.log(mathsMarks + studentName);
let x = Number(mathsMarks + studentName);
console.log(typeof x);
console.log(x);
console.log(x ** 0);
let e = 7;
let t = 4;
let q = 8;
let v = e + t;
console.log(v);
console.log(typeof v);
let f = String(v);
console.log(typeof f);
console.log('i love nature');
console.log("i love ");